import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import TableList from '../components/tableList'
import { useMemo } from 'react'
import dataJson from '../components/data.json';

const Home: NextPage = () => {

    const allData = useMemo(()=> dataJson,[]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Prueba Table App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <TableList allData = {allData.table1}/>
        <TableList allData = {allData.table2}/>
      </div>
    </div>
  )
}

export default Home
